# Generated by Django 5.2.11 on 2026-02-16 03:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_id",
                    models.CharField(
                        help_text="Unique medical record identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Patient's date of birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        help_text="Patient's gender",
                        max_length=1,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        help_text="Patient's blood type (if known)",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        blank=True,
                        help_text="Health insurance policy number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(help_text="Primary address line", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Secondary address line (apartment, suite, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state",
                    models.CharField(help_text="State or province", max_length=50),
                ),
                (
                    "postal_code",
                    models.CharField(help_text="Postal or ZIP code", max_length=20),
                ),
                (
                    "country",
                    models.CharField(
                        default="United States", help_text="Country", max_length=100
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        help_text="Primary phone number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        help_text="Secondary phone number (optional)",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email_personal",
                    models.EmailField(
                        blank=True,
                        help_text="Personal email address (separate from login email)",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_record",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["medical_id"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Emergency contact's full name", max_length=100
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("grandparent", "Grandparent"),
                            ("grandchild", "Grandchild"),
                            ("friend", "Friend"),
                            ("neighbor", "Neighbor"),
                            ("caregiver", "Caregiver"),
                            ("other", "Other"),
                        ],
                        help_text="Relationship to patient",
                        max_length=20,
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        help_text="Primary phone number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        help_text="Secondary phone number (optional)",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address (optional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False, help_text="Primary emergency contact"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this contact",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["-is_primary_contact", "name"],
            },
        ),
    ]
