# Generated by Django 4.2.10 on 2026-04-20 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_medication_fulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='risk_level',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('safe', 'Safe')], default='safe', help_text='Drug-allergy risk classification — FR-Ph-4 / PBI-S4-17', max_length=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Numeric risk score from DrugAllergyRiskEngine (0=safe, 50=medium, 75=high, 100=critical)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_id',
            field=models.CharField(db_index=True, help_text='Unique medical record identifier', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Type of action performed', max_length=10)),
                ('model_name', models.CharField(help_text='Django model class name that was accessed or changed', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Primary key of the affected object', max_length=50)),
                ('object_repr', models.TextField(blank=True, help_text='String representation of the affected object at time of action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address extracted from REMOTE_ADDR', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred — set automatically, cannot be changed')),
                ('changes_summary', models.TextField(blank=True, help_text='JSON-encoded diff of old vs new field values for update events')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
