# Generated by Django 4.2.10 on 2026-02-09 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacy', 'Pharmacy Personnel'), ('admin', 'System Administrator')], help_text="User's role in the patient monitoring system", max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or ward assignment', max_length=100)),
                ('license_number', models.CharField(blank=True, help_text='Professional license number (for medical staff)', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
