# Generated by Django 4.2.10 on 2026-03-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_assigned_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies (medications, food, environmental) — visible to Doctor/Nurse/Pharmacy/Admin, hidden from Patient in admin — FR-Ph-3'),
        ),
    ]
