# Generated by Django 4.2.10 on 2026-03-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patient_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(help_text='Scheduled date and time of the appointment')),
                ('appointment_type', models.CharField(choices=[('initial_consultation', 'Initial Consultation'), ('follow_up', 'Follow-Up'), ('routine_checkup', 'Routine Check-Up'), ('lab_review', 'Lab Review'), ('urgent_care', 'Urgent Care')], help_text='Category of appointment', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', help_text='Current status of the appointment', max_length=15)),
                ('location', models.CharField(help_text='Room or clinic name where the appointment takes place', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional clinical or administrative notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor responsible for this appointment', limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to='core.userprofile')),
                ('patient', models.ForeignKey(help_text='Patient for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_datetime'],
            },
        ),
    ]
